# Generated by Django 5.2.5 on 2025-08-18 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimodelresult",
            options={"ordering": ["-created_at"]},
        ),
    ]
