# Generated by Django 5.2.5 on 2025-08-19 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_aimodelresult_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="session_id",
            new_name="session",
        ),
    ]
